spring:
  application:
    name: TinyUrlApplication

  liquibase:
    change-log: db/changelog/changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://0.0.0.0:5433/tiny_url}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootroot}
    driver-class-name: org.postgresql.Driver

#    url: jdbc:postgresql://0.0.0.0:5433/tiny_url
#    username: postgres
#    password: rootroot
#    driver-class-name: org.postgresql.Driver
#    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

server:
  port: 8080