version: '3.8'

services:
  db:
    container_name: "postgres_db_app123"
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5433:5432"

volumes:
  postgres_data: