spring:
  application:
    name: RestfulCrudToDoApp

  liquibase:
    change-log: db/changelog/changelog-master.yml


  datasource:
    url: ${DB_URL:jdbc:postgresql://db_hibernate_postgres:5432/crud_app_hibernate}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rootroot}
    driver-class-name: org.postgresql.Driver

