spring:
  application:
    name: RestfulCrudToDoApp
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: db/changelog/changelog-master.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

