apiVersion: v1
kind: Service
metadata:
  name: app-tiny-url-service
spec:
  type: NodePort
  selector:
    app: app-tiny-url
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080