apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tiny-url-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-tiny-url
  template:
    metadata:
      labels:
        app: db-tiny-url
    spec:
      containers:
        - name: db-tiny-url-container
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD

