version: '3.8'

services:
  app_code_reader_service:
    container_name: "code_reader_service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    driver: bridge