version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"
