version: '3.8'

services:
  app_registration_service-local:
    container_name: "registration_service-local"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - local-db
    networks:
      - shared_network

  local-db:
    container_name: ${POSTGRES_HOST_LOCAL}
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB_LOCAL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME_LOCAL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_LOCAL}
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
      - ./infrastructure/db/create-db-local.sql:/docker-entrypoint-initdb.d/create_db-local.sql
    ports:
      - "5433:5432"
    networks:
      - shared_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shared_network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - shared_network

volumes:
  postgres_data_new:

networks:
  shared_network:
    external: true
    driver: bridge